# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindowArGkfV.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QStatusBar,
    QWidget)
import recursos_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.ApplicationModal)
        MainWindow.resize(434, 526)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.LB_Fondo = QLabel(self.centralwidget)
        self.LB_Fondo.setObjectName(u"LB_Fondo")
        self.LB_Fondo.setGeometry(QRect(80, 20, 51, 16))
        self.LB_Texto = QLabel(self.centralwidget)
        self.LB_Texto.setObjectName(u"LB_Texto")
        self.LB_Texto.setGeometry(QRect(290, 20, 41, 16))
        self.LB_BG_Rojo = QLabel(self.centralwidget)
        self.LB_BG_Rojo.setObjectName(u"LB_BG_Rojo")
        self.LB_BG_Rojo.setGeometry(QRect(20, 50, 41, 16))
        self.LB_BG_Verde = QLabel(self.centralwidget)
        self.LB_BG_Verde.setObjectName(u"LB_BG_Verde")
        self.LB_BG_Verde.setGeometry(QRect(80, 50, 41, 16))
        self.LB_BG_Azul = QLabel(self.centralwidget)
        self.LB_BG_Azul.setObjectName(u"LB_BG_Azul")
        self.LB_BG_Azul.setGeometry(QRect(150, 50, 41, 16))
        self.LB_FG_Rojo = QLabel(self.centralwidget)
        self.LB_FG_Rojo.setObjectName(u"LB_FG_Rojo")
        self.LB_FG_Rojo.setGeometry(QRect(230, 50, 41, 16))
        self.LB_FG_Verde = QLabel(self.centralwidget)
        self.LB_FG_Verde.setObjectName(u"LB_FG_Verde")
        self.LB_FG_Verde.setGeometry(QRect(290, 50, 51, 16))
        self.LB_FG_Azul = QLabel(self.centralwidget)
        self.LB_FG_Azul.setObjectName(u"LB_FG_Azul")
        self.LB_FG_Azul.setGeometry(QRect(370, 50, 41, 16))
        self.SB_BG_Rojo = QSpinBox(self.centralwidget)
        self.SB_BG_Rojo.setObjectName(u"SB_BG_Rojo")
        self.SB_BG_Rojo.setGeometry(QRect(10, 80, 51, 22))
        self.SB_BG_Rojo.setFrame(False)
        self.SB_BG_Rojo.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_BG_Rojo.setMaximum(255)
        self.SB_BG_Verde = QSpinBox(self.centralwidget)
        self.SB_BG_Verde.setObjectName(u"SB_BG_Verde")
        self.SB_BG_Verde.setGeometry(QRect(77, 80, 50, 22))
        self.SB_BG_Verde.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_BG_Verde.setMaximum(255)
        self.SB_BG_Azul = QSpinBox(self.centralwidget)
        self.SB_BG_Azul.setObjectName(u"SB_BG_Azul")
        self.SB_BG_Azul.setGeometry(QRect(142, 80, 51, 22))
        self.SB_BG_Azul.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_BG_Azul.setMaximum(255)
        self.SB_FG_Rojo = QSpinBox(self.centralwidget)
        self.SB_FG_Rojo.setObjectName(u"SB_FG_Rojo")
        self.SB_FG_Rojo.setGeometry(QRect(220, 80, 51, 22))
        self.SB_FG_Rojo.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_FG_Rojo.setMaximum(255)
        self.SB_FG_Rojo.setValue(255)
        self.SB_FG_Verde = QSpinBox(self.centralwidget)
        self.SB_FG_Verde.setObjectName(u"SB_FG_Verde")
        self.SB_FG_Verde.setGeometry(QRect(290, 80, 51, 22))
        self.SB_FG_Verde.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_FG_Verde.setMaximum(255)
        self.SB_FG_Verde.setValue(255)
        self.SB_FG_Azul = QSpinBox(self.centralwidget)
        self.SB_FG_Azul.setObjectName(u"SB_FG_Azul")
        self.SB_FG_Azul.setGeometry(QRect(360, 80, 51, 22))
        self.SB_FG_Azul.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_FG_Azul.setMaximum(255)
        self.SB_FG_Azul.setValue(255)
        self.SL_BG_Rojo = QSlider(self.centralwidget)
        self.SL_BG_Rojo.setObjectName(u"SL_BG_Rojo")
        self.SL_BG_Rojo.setGeometry(QRect(20, 110, 22, 160))
        self.SL_BG_Rojo.setMaximum(255)
        self.SL_BG_Rojo.setPageStep(1)
        self.SL_BG_Rojo.setOrientation(Qt.Vertical)
        self.SL_BG_Verde = QSlider(self.centralwidget)
        self.SL_BG_Verde.setObjectName(u"SL_BG_Verde")
        self.SL_BG_Verde.setGeometry(QRect(85, 109, 22, 160))
        self.SL_BG_Verde.setMaximum(255)
        self.SL_BG_Verde.setPageStep(1)
        self.SL_BG_Verde.setOrientation(Qt.Vertical)
        self.SL_BG_Azul = QSlider(self.centralwidget)
        self.SL_BG_Azul.setObjectName(u"SL_BG_Azul")
        self.SL_BG_Azul.setGeometry(QRect(150, 108, 22, 160))
        self.SL_BG_Azul.setMaximum(255)
        self.SL_BG_Azul.setPageStep(1)
        self.SL_BG_Azul.setOrientation(Qt.Vertical)
        self.SL_FG_Rojo = QSlider(self.centralwidget)
        self.SL_FG_Rojo.setObjectName(u"SL_FG_Rojo")
        self.SL_FG_Rojo.setGeometry(QRect(230, 107, 22, 160))
        self.SL_FG_Rojo.setMaximum(255)
        self.SL_FG_Rojo.setPageStep(1)
        self.SL_FG_Rojo.setValue(255)
        self.SL_FG_Rojo.setOrientation(Qt.Vertical)
        self.SL_FG_Verde = QSlider(self.centralwidget)
        self.SL_FG_Verde.setObjectName(u"SL_FG_Verde")
        self.SL_FG_Verde.setGeometry(QRect(300, 107, 22, 160))
        self.SL_FG_Verde.setMaximum(255)
        self.SL_FG_Verde.setPageStep(1)
        self.SL_FG_Verde.setValue(255)
        self.SL_FG_Verde.setOrientation(Qt.Vertical)
        self.SL_FG_Azul = QSlider(self.centralwidget)
        self.SL_FG_Azul.setObjectName(u"SL_FG_Azul")
        self.SL_FG_Azul.setGeometry(QRect(370, 107, 22, 160))
        self.SL_FG_Azul.setMaximum(255)
        self.SL_FG_Azul.setPageStep(1)
        self.SL_FG_Azul.setValue(255)
        self.SL_FG_Azul.setOrientation(Qt.Vertical)
        self.LB_Muestra = QLabel(self.centralwidget)
        self.LB_Muestra.setObjectName(u"LB_Muestra")
        self.LB_Muestra.setGeometry(QRect(60, 300, 301, 101))
        self.LB_Muestra.setStyleSheet(u"background-color: #000000; color: #FFFFFF; font-family: Arial; font-size: 48px;")
        self.LB_Muestra.setAlignment(Qt.AlignCenter)
        self.LB_RES_Fondo = QLabel(self.centralwidget)
        self.LB_RES_Fondo.setObjectName(u"LB_RES_Fondo")
        self.LB_RES_Fondo.setGeometry(QRect(70, 430, 51, 16))
        self.RES_Fondo = QLabel(self.centralwidget)
        self.RES_Fondo.setObjectName(u"RES_Fondo")
        self.RES_Fondo.setGeometry(QRect(130, 430, 61, 16))
        self.BTN_Copiar_Fondo = QPushButton(self.centralwidget)
        self.BTN_Copiar_Fondo.setObjectName(u"BTN_Copiar_Fondo")
        self.BTN_Copiar_Fondo.setGeometry(QRect(229, 420, 111, 32))
        self.LB_RES_Texto = QLabel(self.centralwidget)
        self.LB_RES_Texto.setObjectName(u"LB_RES_Texto")
        self.LB_RES_Texto.setGeometry(QRect(70, 450, 51, 16))
        self.RES_Texto = QLabel(self.centralwidget)
        self.RES_Texto.setObjectName(u"RES_Texto")
        self.RES_Texto.setGeometry(QRect(130, 450, 58, 16))
        self.BTN_Copiar_Texto = QPushButton(self.centralwidget)
        self.BTN_Copiar_Texto.setObjectName(u"BTN_Copiar_Texto")
        self.BTN_Copiar_Texto.setGeometry(QRect(230, 445, 111, 32))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.LB_Fondo.setText(QCoreApplication.translate("MainWindow", u"FONDO", None))
        self.LB_Texto.setText(QCoreApplication.translate("MainWindow", u"TEXTO", None))
        self.LB_BG_Rojo.setText(QCoreApplication.translate("MainWindow", u"ROJO", None))
        self.LB_BG_Verde.setText(QCoreApplication.translate("MainWindow", u"VERDE", None))
        self.LB_BG_Azul.setText(QCoreApplication.translate("MainWindow", u"AZUL", None))
        self.LB_FG_Rojo.setText(QCoreApplication.translate("MainWindow", u"ROJO", None))
        self.LB_FG_Verde.setText(QCoreApplication.translate("MainWindow", u"VERDE", None))
        self.LB_FG_Azul.setText(QCoreApplication.translate("MainWindow", u"AZUL", None))
        self.LB_Muestra.setText(QCoreApplication.translate("MainWindow", u"Muestra", None))
        self.LB_RES_Fondo.setText(QCoreApplication.translate("MainWindow", u"FONDO", None))
        self.RES_Fondo.setText(QCoreApplication.translate("MainWindow", u"#000000", None))
        self.BTN_Copiar_Fondo.setText(QCoreApplication.translate("MainWindow", u"Copiar Fondo", None))
        self.LB_RES_Texto.setText(QCoreApplication.translate("MainWindow", u"TEXTO", None))
        self.RES_Texto.setText(QCoreApplication.translate("MainWindow", u"#FFFFFF", None))
        self.BTN_Copiar_Texto.setText(QCoreApplication.translate("MainWindow", u"Copiar Texto", None))
    # retranslateUi

