"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    'MainWindow_ui.py', 
    'MainWindow.py', 
    'recursos_rc.py'
]
OPTIONS = {
    'iconfile': 'color_select.png'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
